# Generated by Django 4.0.6 on 2022-07-11 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='type',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='type',
            field=models.ManyToManyField(related_name='Types', through='TODO_list.TaskType', to='TODO_list.type'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='task_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_type', to='TODO_list.taskmodel', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_type', to='TODO_list.type', verbose_name='Имя типа'),
        ),
    ]
