# Generated by Django 4.0.6 on 2022-07-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_list', '0002_tasktype_remove_taskmodel_type_taskmodel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='type',
            field=models.ManyToManyField(related_name='Type', through='TODO_list.TaskType', to='TODO_list.type'),
        ),
    ]
