# Generated by Django 4.0.6 on 2022-07-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_list', '0003_alter_taskmodel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='type',
            new_name='types',
        ),
    ]
