# Generated by Django 4.0.6 on 2022-07-24 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_list', '0004_rename_type_taskmodel_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=50, verbose_name='Имя проекта')),
                ('project_de', models.TextField(max_length=1000, verbose_name='Описание проекта')),
                ('created_time', models.DateField(verbose_name='Дата создания')),
                ('updated_time', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('task_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Task_project', to='TODO_list.taskmodel', verbose_name='Задачи проекта')),
            ],
        ),
    ]
