# Generated by Django 4.0.6 on 2022-08-13 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TODO_list', '0005_project_taskmodel_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
